### ISSUE TITLE
ImageGlass installation/upgrade issue with 8.10.9.27

### ISSUE THREAD

**Issue by asheroto** [Starz0r/ChocolateyPackagingScripts#17]
Hello,

There appears to be an issue with the package installation. Here's a screenshot of the error.

![image](https://github.com/Starz0r/ChocolateyPackagingScripts/assets/49938263/561ecddc-26c5-428b-8514-9632295b162e)

When using the same MSI, now in the lib-bad folder, running manually, choosing "Typical" install, the installation completed successfully.

ImageGlass devs may have changed something on their end. I was just upgrading from an older 8.x version when I received this error.

**Comment by Starz0r** [comment]
I personally had no issue with local installation, looks like the problem could exist on your end.

MSI's Error Code 1603 is a failure mode that can be achieved in multiple different ways, including having the application open elsewhere. You can try restarting the machine, uninstalling the package and reinstalling from scratch, or looking [here](https://stackoverflow.com/a/50950235) for more options on what you can do. If there are some interesting entries in your system's Event Log, that you think would be necessary to fixing this, feel free to post them.

**Comment by asheroto** [comment]
Ah, sorry. This is not a packaging issue.

ImageGlass has had a lot of issues with things breaking lately. Although the setup completed, the repair failed, so something else is wrong. Will continue to troubleshoot on my end for resolution. Thanks!
