### ISSUE TITLE
Omnisharp outdated

### ISSUE THREAD

**Issue by tricktux** [Starz0r/ChocolateyPackagingScripts#4]
Thanks for maintaining all this packages!

**Comment by Starz0r** [comment]
Thanks.

I'm getting to it, procrastinating because OmniSharp changed their project structure again, so I have to find which executables get blacklisted from shims, which has to be done manually, and is just very tedious.

**Comment by tricktux** [comment]
😂😂😂😂
  

  
Very nice setup you have there with python. I maintain neovim, might look into copying your setup.
  

  

  
  
 Thanks,  
  

  
Reinaldo Molina
  
  
  
  
  
  
>
