### ISSUE TITLE
Update dotnet4.7.2 dependencies

### ISSUE THREAD

**Issue by rollingmoai** [Starz0r/ChocolateyPackagingScripts#8]
> This package is deprecated.
> End users should install the [dotnetfx](https://chocolatey.org/packages/dotnetfx) package.
> Package maintainers should depend on the [netfx-4.7.2](https://chocolatey.org/packages/netfx-4.7.2) package.

 Packages that need to be fixed:

* `tweetdeck`
* `omnisharp`

Maybe I missed something else, please fix.

**Comment by Starz0r** [comment]
Looks like `tweetdeck` no longer relies on .NET Framework 4.7.2, and has moved on to .NET 7. As for `omnisharp`, they still provide versions using .NET Framework 4, but are moving towards .NET 6. I'm not using the .NET 6 versions of `omnisharp`, so I will update for those.

Sorry this took so long to implement :(.

**Comment by rollingmoai** [comment]
All good. I already switched to Winget + Scoop a long time ago due to many cases of outdated packages like this 😅.

**Comment by Starz0r** [comment]
That's fine, I hope Winget serves you well.

Although, you do mention "outdated" packages, and the packages I manage are usually updated 1-3 days from the time updates are dropped. The issue you originally opened was about the wrong runtime package dependency being listed instead of the right one. Unless this was referring to something else? My packages usually don't stay out of date for too long...

**Comment by rollingmoai** [comment]
I was referring to something else. Although, in cases like this, it would be easy to PR a fix directly in winget-pkgs over some maintainer's possibly dead repo (not saying yours) or take package ownership (in which case it might be their turn to disappear afterwards).

**Comment by Starz0r** [comment]
That's understandable. I recently just inherited another dead package from a maintainer who hasn't been around in years. I'm not really sure how it works with Winget, if Microsoft does all the packages then I guess you'll never have to worry (which I assume is the truth).

**Comment by rollingmoai** [comment]
> if Microsoft does all the packages then I guess you'll never have to worry (which I assume is the truth).

Not really. The difference is that all packages are centralized, everyone can contribute to it (without having to go through the package ownership process), and there is easy tooling to update and automate packages (See [WingetCreate](https://github.com/microsoft/winget-create), [Komac](https://github.com/russellbanks/Komac), and [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser)). For non-package vendors, there also happens to be an external automation repo managed by the Winget Releaser author, which you can contribute to (https://github.com/vedantmgoyal2009/winget-manifests-manager).

I think this article summarizes the pain points of Chocolatey (From the AppGet author, which later became the inspiration for Winget): https://keivan.io/why-chocolatey-is-broken/
