### ISSUE TITLE
Dependencies for `ModernFlyouts 0.10.0-beta1` are wrong

### ISSUE THREAD

**Issue by brian6932** [Starz0r/ChocolateyPackagingScripts#9]
Listed dependencies currently are:

        dotnet (≥ 6.0.0-rc2214805)
        dotnet-6.0-runtime (≥ 6.0.0-rc2214805)
While it should be:

        dotnet (≥ 6.0.0-rc2214805)
        dotnet-6.0-desktopruntime (≥ 6.0.0-rc2215016)

**Comment by Starz0r** [comment]
Nothing I could do about it at the time. New versions for `dotnet` were taking too long to publish, so I imagined if people were updating their system packages on time, this would not be a big issue. Right now, you can just install `dotnet (≥ 6.0.0)` to avoid this. Future versions of the ModernFlyouts package will also target this.
